export const DONATION_CREATE_REQUEST = 'DONATION_CREATE_REQUEST';
export const DONATION_CREATE_SUCCESS = 'DONATION_CREATE_SUCCESS';
export const DONATION_CREATE_FAIL = 'DONATION_CREATE_FAIL';
export const DONATION_CREATE_RESET = 'DONATION_CREATE_RESET';

export const DONATION_WITHOUT_LOGIN_REQUEST = 'DONATION_WITHOUT_LOGIN_REQUEST';
export const DONATION_WITHOUT_LOGIN_SUCCESS = 'DONATION_WITHOUT_LOGIN_SUCCESS';
export const DONATION_WITHOUT_LOGIN_FAIL = 'DONATION_WITHOUT_LOGIN_FAIL';
export const DONATION_WITHOUT_LOGIN_RESET = 'DONATION_WITHOUT_LOGIN_RESET';

export const DONATION_MY_LIST_REQUEST = 'DONATION_MY_LIST_REQUEST';
export const DONATION_MY_LIST_SUCCESS = 'DONATION_MY_LIST_SUCCESS';
export const DONATION_MY_LIST_FAIL = 'DONATION_MY_LIST_FAIL';

export const DONATION_LIST_REQUEST = 'DONATION_LIST_REQUEST';
export const DONATION_LIST_SUCCESS = 'DONATION_LIST_SUCCESS';
export const DONATION_LIST_FAIL = 'DONATION_LIST_FAIL';

export const DONATION_USER_LIST_REQUEST = 'DONATION_USER_LIST_REQUEST';
export const DONATION_USER_LIST_SUCCESS = 'DONATION_USER_LIST_SUCCESS';
export const DONATION_USER_LIST_FAIL = 'DONATION_USER_LIST_FAIL';
